// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbqwpddzpjuwksfvyxsh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImticXdwZGR6cGp1d2tzZnZ5eHNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NTYyMjQsImV4cCI6MjA3MTEzMjIyNH0.8lb4MKjCmmxIuEEF7c4gJlOrpdgnoZv3_H__B_5NCCo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});